### ISSUE TITLE
isTextExpanderTouchInstalled always returns false on iPad

### ISSUE THREAD

**Issue by youens** [SmileSoftware/TextExpanderTouchSDK#18]
We're seeing an issue where calling `[SMTEDelegateController isTextExpanderTouchInstalled]` on iPad always returns `false`. We've had TE3 installed, as well as TE4. The effect in our app is pretty large in that it prevents any use of TE.

Perhaps it's an issue on our side, but it works fine on iPhone (same project, different target). Can anyone confirm that it does in fact work properly in all scenarios?

**Comment by SmilinBrian** [comment]
This method is very simple:
```
+ (BOOL)isTextExpanderTouchInstalled {
	return [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:@"tetouch://"]];
}
```

Probably you are missing these instructions from the [Readme instructions](https://github.com/SmileSoftware/TextExpanderTouchSDK#allow-querying-and-opening-the-textexpander-touch-app)

## Allow querying and opening the TextExpander touch app ##

As of iOS 9 you must "whitelist" TextExpander URL schemes so that openURL and canOpenURL can work properly.

Select your app's target
- Click on "Info"
- Add a LSApplicationQueriesSchemes key (if your project does not yet have one) with an Array value
- Add three TextExpander URL scheme values to this array: tetouch, tetouch-xc, and tetouch-settings
